name: Update CHANGELOG

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update CHANGELOG
        run: |
          git log --format=%s > CHANGELOG.md
